# This file was generated by GoReleaser. DO NOT EDIT.
cask "gotpm" do
  version "0.6.0"

  on_macos do
    on_arm do
      sha256 "4d0a767e20f988cb80a8c64d367f96bfefad622400fa989ff2724a3ebb58acb9"
      url "https://github.com/npikall/gotpm/releases/download/v#{version}/gotpm_v#{version}_darwin_arm64"
      binary "gotpm_v0.6.0_darwin_arm64", target: "gotpm"
    end
    on_intel do
      sha256 "3026ca3f7af33d5733382fcb6902ee2cc0268d03d6874a6f0dff69cba2eabb70"
      url "https://github.com/npikall/gotpm/releases/download/v#{version}/gotpm_v#{version}_darwin_amd64"
      binary "gotpm_v0.6.0_darwin_amd64", target: "gotpm"
    end
  end
  on_linux do
    on_arm do
      sha256 "c93eb8db308be53a9e3d6a1c2ba30af5b98a093b43008102a11f587f9e2fdde0"
      url "https://github.com/npikall/gotpm/releases/download/v#{version}/gotpm_v#{version}_linux_arm64"
      binary "gotpm_v0.6.0_linux_arm64", target: "gotpm"
    end
    on_intel do
      sha256 "de5cf3c8fb6e58e9597a5a73d8b160cd1c568de92f4bba82666a4ca12c4e5554"
      url "https://github.com/npikall/gotpm/releases/download/v#{version}/gotpm_v#{version}_linux_amd64"
      binary "gotpm_v0.6.0_linux_amd64", target: "gotpm"
    end
  end

  name "gotpm"
  desc "A minimal package manager for Typst"
  homepage "https://github.com/npikall/gotpm"

  livecheck do
    skip "Auto-generated on release."
  end

  # No zap stanza required
end
