# This file was generated by GoReleaser. DO NOT EDIT.
cask "gotpm" do
  version "0.7.0"

  on_macos do
    on_arm do
      sha256 "23d24f78e521e9cf125d21e4adc9ad7007295f007ac17c8328488142582aeba5"
      url "https://github.com/npikall/gotpm/releases/download/v#{version}/gotpm_v#{version}_darwin_arm64"
      binary "gotpm_v0.7.0_darwin_arm64", target: "gotpm"
    end
    on_intel do
      sha256 "42c480d4ea350a8365d7fdfce8140f29823b2365fc42d38fa261d925c4e1edae"
      url "https://github.com/npikall/gotpm/releases/download/v#{version}/gotpm_v#{version}_darwin_amd64"
      binary "gotpm_v0.7.0_darwin_amd64", target: "gotpm"
    end
  end
  on_linux do
    on_arm do
      sha256 "ac38f2a90395c1c46dccb047b6dc4eade8b9a87198c717e594edef97ec11bfdc"
      url "https://github.com/npikall/gotpm/releases/download/v#{version}/gotpm_v#{version}_linux_arm64"
      binary "gotpm_v0.7.0_linux_arm64", target: "gotpm"
    end
    on_intel do
      sha256 "d4f7c2fe75271670dea43934baf66b367d3246b8e2a44fe836948c34607ca8ae"
      url "https://github.com/npikall/gotpm/releases/download/v#{version}/gotpm_v#{version}_linux_amd64"
      binary "gotpm_v0.7.0_linux_amd64", target: "gotpm"
    end
  end

  name "gotpm"
  desc "A minimal package manager for Typst"
  homepage "https://github.com/npikall/gotpm"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
    end
  end

  # No zap stanza required
end
