# This file was generated by GoReleaser. DO NOT EDIT.
cask "gotpm" do
  version "0.5.2"

  on_macos do
    on_arm do
      sha256 "dd835a21b1ab667c2d3628faeeaff753cae60437ae317433a0966630490741a7"
      url "https://github.com/npikall/gotpm/releases/download/v#{version}/gotpm_v#{version}_darwin_arm64"
      binary "gotpm_v0.5.2_darwin_arm64", target: "gotpm"
    end
    on_intel do
      sha256 "156087472daa0ad42c34a674709fd49a2ff234c9608ebb948c3227d681617439"
      url "https://github.com/npikall/gotpm/releases/download/v#{version}/gotpm_v#{version}_darwin_amd64"
      binary "gotpm_v0.5.2_darwin_amd64", target: "gotpm"
    end
  end
  on_linux do
    on_arm do
      sha256 "77d1954e5a630e4e22d5975963900a1310706566123aac1baf68fd3da8ebfbf8"
      url "https://github.com/npikall/gotpm/releases/download/v#{version}/gotpm_v#{version}_linux_arm64"
      binary "gotpm_v0.5.2_linux_arm64", target: "gotpm"
    end
    on_intel do
      sha256 "bcdc69e06120c40b495a3d7b85ba081d2f54ee81c1c7b4a60307ab09348fb11a"
      url "https://github.com/npikall/gotpm/releases/download/v#{version}/gotpm_v#{version}_linux_amd64"
      binary "gotpm_v0.5.2_linux_amd64", target: "gotpm"
    end
  end

  name "gotpm"
  desc "A minimal package manager for Typst"
  homepage "https://github.com/npikall/gotpm"

  livecheck do
    skip "Auto-generated on release."
  end

  # No zap stanza required
end
